version: "3.8"

services:
  c-consul:
    container_name: c-consul
    image: consul:${CONSUL_VERSION}
    env_file:
      - ./consul/.env
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600"
    restart: always

  c-mysql:
    container_name: c-mysql
    image: mysql:${MYSQL_VERSION}
    build:
      context: ./mysql
    env_file:
      - ./mysql/.env
    volumes:
      - ./var/log/mysql:/var/log/mysql
      - ./var/lib/mysql:/var/lib/mysql
      - ./mysql/mysql-schema.sql:/docker-entrypoint-initdb.d/mysql-scheme.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  c-redis:
    container_name: c-redis
    image: redis:${REDIS_VERSION}
    build:
      context: ./redis
    volumes:
      - ./var/data/redis:/data/redis
    ports:
      - "6379:6379"

  c-zookeeper:
    container_name: c-zookeeper
    image: zookeeper:${ZOOKEEPER_VERSION}
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181

  c-kafka:
    container_name: c-kafka
    image: bitnami/kafka:${KAFKA_VERSION}
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
    depends_on:
      - c-zookeeper

  c-nginx:
    container_name: c-nginx
    image: nginx:${NGINX_VERSION}
    build:
      context: ./nginx
    volumes:
      - ${PHP_WWW_PATH}:/var/www/:cached
      - ./nginx/sites/:/etc/nginx/sites-available/
      - ./var/log/nginx/:/var/log/nignx/
#    depends_on:
#      - php56-fpm
#      - php74-fpm
#      - php81-fpm
    ports:
      - "80:80"

  c-nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: c-nacos
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    volumes:
      - ./var/log/nacos/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      c-mysql:
        condition: service_healthy
    restart: always

  c-postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: c-postgres
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"

  c-kong:
    image: kong:${KONG_GATEWAY_VERSION}
    container_name: c-kong
    env_file:
      - ./kong/.env
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8444:8444"
